### PR TITLE
revised to fix flaw in behavior of dedup_rows

### PR DESCRIPTION
**Pull request by osunderdog**
While trying out visidata v2.-2 and investigating the plugin framework I found your repo.  (thankyou!) It appears as though the dedupe_rows did not work as described.  I fixed it by using vs.rows assignment.   Please let me know if you have suggestions on how I can make this PR better.
thanks.

### CODE REVIEW

**Comment by jsvine** [comment]
Thanks, @osunderdog. The plugins in this repo currently target VisiData 1.5.2, the latest stable version. I’ve held off on modifying them for 2.x until that version is stable. That said, I’d be open to modifying the plugin to work in both 1.5.2 and 2.x simultaneously, if there’s a way to do that.

One thing that would be helpful: You say that `dedupe_rows` “did not work as described” — could you explain more?

(Relatedly: @anjakefala, any pointers on what changed in 2.x that might underlie what @osunderdog has observed? Thanks!)

**Comment by anjakefala** [comment]
@jsvine I do not see anything in there that is `v1.5.2` specific! 

Also, the plugin works as expected for me on `develop`. :thinking: 

There are some changes I could suggest depending on other expected behaviour (e.g. what do you want to happen when the sheet reloads). None of them are `v2.x` specific. 

I suspect the change suggested in the PR might make things slower for larger datasets? The sheet rows would need to be completely re-added before you see your data.

**Comment by jsvine** [comment]
Thanks, @anjakefala! Really appreciate you taking a look.

**Comment by saulpw** [comment]
Hey @osunderdog, I'm not sure why the current code doesn't work for you.  It's important to add rows one at a time, so that the results are updated continuously (it runs asynchronously and could take a lot of time on large datasets).  `addRow` is also important to call for certain plugins.  Maybe you overrode `addRow` and forgot to call `super().addRow(row, index=index)`?

**Comment by osunderdog** [comment]
I'm a complete novice at this package (visidata) so not surprised that my first attempt is questionable.  I'll try to come up with a reasonable way to demo the issue I see.

**Pull request closed without merging**
